"""
NexusHive Bridge — Re-export from canonical location.
DO NOT edit this file. Edit src/integrations/nexus_hive_bridge.py instead.
"""

from src.integrations.nexus_hive_bridge import NexusHiveBridge

__all__ = ["NexusHiveBridge"]
