"""
Provider catalog inspired by openhuman's inference-provider-catalog.md.

25+ BYOK providers preconfigurados. El user los activa en Config con su API key.
Patron: cada provider es un Profile en ProviderRegistry, con base_url + auth style.
"""

PROVIDER_CATALOG = [
    # === FREE / OPENCODE ZEN ===
    {
        "id": "cloud-zen",
        "name": "OpenCode Zen (free)",
        "base_url": "https://opencode.ai/zen/v1",
        "api_key_env": "OPENCODE_API_KEY",
        "auth_style": "bearer",
        "default_model": "deepseek-v4-flash-free",
        "models": ["deepseek-v4-flash-free", "nemotron-3-super-free", "big-pickle"],
        "tags": ["cloud", "fast", "free"],
        "description": "Cloud rapido via OpenCode Zen. Free tier disponible.",
    },
    {
        "id": "opencode-go",
        "name": "OpenCode Go (subscription)",
        "base_url": "https://opencode.ai/zen/go/v1",
        "api_key_env": "OPENCODE_API_KEY",
        "auth_style": "bearer",
        "default_model": "deepseek-v4-flash",
        "models": ["deepseek-v4-flash", "deepseek-v4-pro", "kimi-k2.5", "kimi-k2.6", "glm-5", "glm-5.1", "mimo-v2.5", "mimo-v2.5-pro"],
        "tags": ["cloud", "subscription", "premium"],
        "description": "Modelos premium via OpenCode Go (kimi, glm, deepseek, mimo).",
    },

    # === MAJOR CLOUD ===
    {
        "id": "openai",
        "name": "OpenAI",
        "base_url": "https://api.openai.com/v1",
        "api_key_env": "OPENAI_API_KEY",
        "auth_style": "bearer",
        "default_model": "gpt-4o-mini",
        "models": ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "o1", "o1-mini", "o3-mini"],
        "tags": ["cloud", "premium"],
        "description": "GPT-4o, o1, o3. Premium.",
    },
    {
        "id": "anthropic",
        "name": "Anthropic",
        "base_url": "https://api.anthropic.com/v1",
        "api_key_env": "ANTHROPIC_API_KEY",
        "auth_style": "anthropic",
        "default_model": "claude-3-5-sonnet-20241022",
        "models": ["claude-3-5-sonnet-20241022", "claude-3-5-haiku-20241022", "claude-3-opus-20240229"],
        "tags": ["cloud", "premium", "anthropic-format"],
        "description": "Claude 3.5/3 Opus. Premium. Formato Anthropic nativo.",
    },
    {
        "id": "google",
        "name": "Google Gemini",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
        "api_key_env": "GEMINI_API_KEY",
        "auth_style": "bearer",
        "default_model": "gemini-1.5-flash",
        "models": ["gemini-1.5-flash", "gemini-1.5-pro", "gemini-2.0-flash-exp"],
        "tags": ["cloud", "fast", "free-tier"],
        "description": "Gemini via OpenAI-compatible endpoint.",
    },
    {
        "id": "deepseek",
        "name": "DeepSeek",
        "base_url": "https://api.deepseek.com/v1",
        "api_key_env": "DEEPSEEK_API_KEY",
        "auth_style": "bearer",
        "default_model": "deepseek-chat",
        "models": ["deepseek-chat", "deepseek-reasoner"],
        "tags": ["cloud", "reasoning", "cheap"],
        "description": "DeepSeek V3 + R1. Muy barato.",
    },
    {
        "id": "groq",
        "name": "Groq",
        "base_url": "https://api.groq.com/openai/v1",
        "api_key_env": "GROQ_API_KEY",
        "auth_style": "bearer",
        "default_model": "llama-3.3-70b-versatile",
        "models": ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768"],
        "tags": ["cloud", "fast", "free-tier"],
        "description": "LLMs en hardware LPU. Muy rapido. Free tier generoso.",
    },
    {
        "id": "mistral",
        "name": "Mistral AI",
        "base_url": "https://api.mistral.ai/v1",
        "api_key_env": "MISTRAL_API_KEY",
        "auth_style": "bearer",
        "default_model": "mistral-large-latest",
        "models": ["mistral-large-latest", "mistral-small-latest", "codestral-latest"],
        "tags": ["cloud", "european"],
        "description": "Mistral Large/Small/Codestral.",
    },
    {
        "id": "xai",
        "name": "xAI (Grok)",
        "base_url": "https://api.x.ai/v1",
        "api_key_env": "XAI_API_KEY",
        "auth_style": "bearer",
        "default_model": "grok-2-latest",
        "models": ["grok-2-latest", "grok-2-mini", "grok-beta"],
        "tags": ["cloud", "x-twitter"],
        "description": "Grok 2 de xAI.",
    },
    {
        "id": "cohere",
        "name": "Cohere",
        "base_url": "https://api.cohere.com/v1",
        "api_key_env": "COHERE_API_KEY",
        "auth_style": "bearer",
        "default_model": "command-r-plus",
        "models": ["command-r-plus", "command-r", "command-light"],
        "tags": ["cloud", "rag", "rerank"],
        "description": "Command R+ con RAG y rerank.",
    },
    {
        "id": "fireworks",
        "name": "Fireworks AI",
        "base_url": "https://api.fireworks.ai/inference/v1",
        "api_key_env": "FIREWORKS_API_KEY",
        "auth_style": "bearer",
        "default_model": "accounts/fireworks/models/llama-v3p3-70b-instruct",
        "models": [
            "accounts/fireworks/models/llama-v3p3-70b-instruct",
            "accounts/fireworks/models/llama-v3p1-8b-instruct",
            "accounts/fireworks/models/mixtral-8x7b-instruct",
            "accounts/fireworks/models/deepseek-v3",
        ],
        "tags": ["cloud", "fast", "cheap"],
        "description": "Fireworks AI: inferencia rapida de modelos open source.",
    },
    {
        "id": "together",
        "name": "Together AI",
        "base_url": "https://api.together.xyz/v1",
        "api_key_env": "TOGETHER_API_KEY",
        "auth_style": "bearer",
        "default_model": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "models": [
            "meta-llama/Llama-3.3-70B-Instruct-Turbo",
            "meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo",
            "Qwen/Qwen2.5-72B-Instruct-Turbo",
        ],
        "tags": ["cloud", "open-source", "cheap"],
        "description": "Together AI: variedad de modelos open source.",
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
        "auth_style": "bearer",
        "default_model": "nex-agi/nex-n2-pro:free",
        "models": [
            "nex-agi/nex-n2-pro:free",
            "nvidia/nemotron-3-ultra-550b-a55b:free", "nvidia/nemotron-3-super-120b-a12b:free",
            "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", "nvidia/nemotron-3-nano-30b-a3b:free",
            "nvidia/nemotron-nano-12b-v2-vl:free", "nvidia/nemotron-nano-9b-v2:free",
            "nvidia/nemotron-3.5-content-safety:free",
            "openai/gpt-oss-120b:free", "openai/gpt-oss-20b:free",
            "openai/gpt-4o-mini", "anthropic/claude-3.5-sonnet",
            "google/gemma-4-31b-it:free", "google/gemma-4-26b-a4b-it:free",
            "google/gemini-pro-1.5",
            "qwen/qwen3-coder:free", "qwen/qwen3-next-80b-a3b-instruct:free",
            "qwen/qwen-2.5-72b-instruct",
            "meta-llama/llama-3.3-70b-instruct:free", "meta-llama/llama-3.2-3b-instruct:free",
            "poolside/laguna-xs.2:free", "poolside/laguna-m.1:free",
            "liquid/lfm-2.5-1.2b-thinking:free", "liquid/lfm-2.5-1.2b-instruct:free",
            "nousresearch/hermes-3-llama-3.1-405b:free",
            "openrouter/owl-alpha",
            "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
        ],
        "tags": ["cloud", "router", "multi-provider"],
        "description": "OpenRouter: un solo endpoint para 100+ modelos.",
    },
    {
        "id": "moonshot",
        "name": "Moonshot (Kimi)",
        "base_url": "https://api.moonshot.ai/v1",
        "api_key_env": "MOONSHOT_API_KEY",
        "auth_style": "bearer",
        "default_model": "moonshot-v1-128k",
        "models": ["moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"],
        "tags": ["cloud", "long-context", "chinese"],
        "description": "Kimi de Moonshot. 128K context, fuerte en chino.",
    },
    {
        "id": "zai",
        "name": "Z.AI (GLM)",
        "base_url": "https://api.z.ai/api/paas/v4",
        "api_key_env": "ZAI_API_KEY",
        "auth_style": "bearer",
        "default_model": "glm-4-plus",
        "models": ["glm-4-plus", "glm-4-air", "glm-4-flash"],
        "tags": ["cloud", "chinese", "cheap"],
        "description": "Z.AI: GLM-4 (modelos chinos competitivos).",
    },
    {
        "id": "minimax",
        "name": "MiniMax",
        "base_url": "https://api.minimax.io/anthropic",
        "api_key_env": "MINIMAX_API_KEY",
        "auth_style": "anthropic",
        "default_model": "MiniMax-M3",
        "models": ["MiniMax-M3"],
        "tags": ["cloud", "anthropic-format"],
        "description": "MiniMax. Formato Anthropic nativo.",
    },
    {
        "id": "cerebras",
        "name": "Cerebras",
        "base_url": "https://api.cerebras.ai/v1",
        "api_key_env": "CEREBRAS_API_KEY",
        "auth_style": "bearer",
        "default_model": "llama-3.3-70b",
        "models": ["llama-3.3-70b", "llama-3.1-8b"],
        "tags": ["cloud", "fast", "wse"],
        "description": "Cerebras WSE: inferencia ultra rapida de Llama.",
    },
    {
        "id": "nvidia",
        "name": "NVIDIA NIM",
        "base_url": "https://integrate.api.nvidia.com/v1",
        "api_key_env": "NVIDIA_API_KEY",
        "auth_style": "bearer",
        "default_model": "meta/llama-3.3-70b-instruct",
        "models": [
            "meta/llama-3.3-70b-instruct",
            "meta/llama-3.1-8b-instruct",
            "nvidia/nemotron-4-340b-instruct",
        ],
        "tags": ["cloud", "gpu-cloud", "free-tier"],
        "description": "NVIDIA NIM. Free tier con Llama 70B.",
    },
    {
        "id": "huggingface",
        "name": "Hugging Face",
        "base_url": "https://router.huggingface.co/v1",
        "api_key_env": "HUGGINGFACE_API_KEY",
        "auth_style": "bearer",
        "default_model": "meta-llama/Llama-3.3-70B-Instruct",
        "models": [
            "meta-llama/Llama-3.3-70B-Instruct",
            "Qwen/Qwen2.5-72B-Instruct",
            "mistralai/Mistral-7B-Instruct-v0.3",
        ],
        "tags": ["cloud", "open-source", "router"],
        "description": "Hugging Face Inference API.",
    },
    {
        "id": "deepinfra",
        "name": "DeepInfra",
        "base_url": "https://api.deepinfra.com/v1/openai",
        "api_key_env": "DEEPINFRA_API_KEY",
        "auth_style": "bearer",
        "default_model": "meta-llama/Llama-3.3-70B-Instruct",
        "models": [
            "meta-llama/Llama-3.3-70B-Instruct",
            "Qwen/Qwen2.5-Coder-32B-Instruct",
        ],
        "tags": ["cloud", "cheap", "open-source"],
        "description": "DeepInfra: open source models a precio bajo.",
    },
    {
        "id": "novita",
        "name": "Novita AI",
        "base_url": "https://api.novita.ai/v3/openai",
        "api_key_env": "NOVITA_API_KEY",
        "auth_style": "bearer",
        "default_model": "meta-llama/llama-3.3-70b-instruct",
        "models": ["meta-llama/llama-3.3-70b-instruct", "qwen/qwen-2.5-72b-instruct"],
        "tags": ["cloud", "cheap"],
        "description": "Novita AI: open source models a bajo costo.",
    },
    {
        "id": "vercel-ai-gateway",
        "name": "Vercel AI Gateway",
        "base_url": "https://ai-gateway.vercel.sh/v1",
        "api_key_env": "VERCEL_AI_GATEWAY_KEY",
        "auth_style": "bearer",
        "default_model": "openai/gpt-4o-mini",
        "models": ["openai/gpt-4o-mini", "anthropic/claude-3.5-sonnet", "google/gemini-1.5-pro"],
        "tags": ["cloud", "router", "unified"],
        "description": "Vercel AI Gateway: un endpoint para todo.",
    },
    {
        "id": "kilocode",
        "name": "Kilo Code",
        "base_url": "https://api.kilo.ai/api/gateway",
        "api_key_env": "KILOCODE_API_KEY",
        "auth_style": "bearer",
        "default_model": "claude-sonnet-4",
        "models": ["claude-sonnet-4", "gpt-4o", "gemini-2.0-flash"],
        "tags": ["cloud", "router", "ide"],
        "description": "Kilo Code gateway para IDEs.",
    },

    # === LOCAL ===
    {
        "id": "ollama",
        "name": "Ollama (local)",
        "base_url": "http://localhost:11434",
        "api_key_env": "",
        "auth_style": "none",
        "default_model": "qwen2.5-coder:7b",
        "models": ["qwen2.5-coder:7b", "llama3.1:8b", "deepseek-r1:8b", "qwen2.5vl:7b", "nemotron-3-nano:4b"],
        "tags": ["local", "fallback", "free"],
        "description": "Ollama local. No requiere API key.",
    },
]


def get_provider_by_id(pid: str) -> dict | None:
    for p in PROVIDER_CATALOG:
        if p["id"] == pid:
            return p
    return None


def list_providers_by_tag(tag: str) -> list[dict]:
    return [p for p in PROVIDER_CATALOG if tag in p.get("tags", [])]


def providers_requiring_key() -> list[dict]:
    return [p for p in PROVIDER_CATALOG if p.get("api_key_env")]
